### ISSUE TITLE
No uploaded files / target address

### ISSUE THREAD

**Issue by cactusoft** [drualcman/BlazorInputFileExtended#1]
I have followed the installation process, I have the component on the page and the various other code in imports etc to make it available.

The demo code seems to show TargetToPostFile as simply a folder name. I am assuming this is within wwwroot, but added same to contentroot just to be safe. But I get this error if I just use a folder name:

**Uploads: Exception: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set. (Parameter 'UploadFilesAsync')**

Not sure how to set BaseAddress so I used a full absolute Uri instead, using baseUri from navManager injected into page, I don't get the error. But nothing happens. After the set delay in async Save, the control just resets like it uploaded the file, but no file uploaded.

Bit stumped. Don't see any errors anywhere at build time, I see the image I selected appear on the page, it's just nothing seems to happen when I hit the upload button. I can step through and see everything seems to work server side, the various steps get triggered, but no file is actually uploaded to the web.

I have tested in multiple browsers Firefox, Vivaldi and Edge. Vivaldi has issue on VisualStudio (blazor crashes out if you cancel the file select dialog) but convention file upload works fine on Firefox and Edge. So pretty sure no issues with those.

Using .NET 6, blazor server

**Comment by drualcman** [comment]
TargetToPostFile is the endpoint where to upload the file. This endpoint need to receive a IFormFile and if you need some other data then can receive also the object. [Here](https://blazorinputfileextended.community-mall.com/how-to-use/basic) you can find the example click on **With Upload Button**.

If continues with some issue, please addtach the code to check.

Thanks

**Comment by drualcman** [comment]
Also to track all the errors or possible response message please use all the [events](https://blazorinputfileextended.community-mall.com/wiki/events)

**Comment by drualcman** [comment]
No more comments. I assume user can fixed the issue.

**Comment by drualcman** [comment]
Closing because no more comments
