### ISSUE TITLE
Tried it and nothing showed on screen

### ISSUE THREAD

**Issue by pjpmccarthy** [drualcman/BlazorInputFileExtended#2]
<InputFileExtended name="picture2" accept="image/*" 
                                   capture="environment" 
                                   ButtonShow="true"
                                   InputTitle="Take Picture"
                                   @onchange="HandleFileSelection" />

**Comment by drualcman** [comment]
InputFileExtended don't have a properties like

name
accept
capture

Also you are using @onchange when must be use OnChange event must be resutn a InputFileChangeEventArgs

Here the code example

```razor
<InputFileExtended ButtonShow="true"
                   InputTitle="Take Picture"
                   OnChange="HandleFileSelection" />

@code {
    void HandleFileSelection(InputFileChangeEventArgs e)
    {
        Console.WriteLine(e.File.Name);
    }
}
```

I use for this example Blazor Webassembly Stand Alone App in NET 7. 

If you want only upload images you can use the property IsImage=true but this is the default action and no need, in this example I can upload pictures and see on the page.

Also I strong suggest use the new version [BlazorBasics.InputFileExtented](https://github.com/drualcman/BlazorBasics.InputFileExtended). Have more capacities and easy to use.
